name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Generate documentation
        run: bun run docs

      - name: Create documentation archive
        run: |
          cd docs
          zip -r ../documentation.zip .

      - name: Create distribution archive
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Publish to npm
        run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this Release

            See the [documentation](https://zavx0z.github.io/html-parser/) for usage examples.

            ### Installation
            ```bash
            bun add @zavx0z/html-parser
            ```
          files: |
            documentation.zip
            dist.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
